# Generated by Django 4.2.4 on 2023-08-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_app', '0005_alter_file_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('-date',), 'verbose_name': 'Лог', 'verbose_name_plural': 'Логи'},
        ),
    ]
